# database.yml, where we declare various DB
# settings and parameters
development:
  adapter: postgresql
  encoding: unicode
  database: s_api_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: s_api_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: s_api_prod
  pool: 2
  username: your_username
  password: your_password